./run.sh ../benchmarks/unsolve-ipc-2016/bag-transport/dom07.pddl ../benchmarks/unsolve-ipc-2016/bag-transport/prob07.pddl set &> ./tests/profile_results/bag-transport___prob07.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/bottleneck/domain.pddl ../benchmarks/unsolve-ipc-2016/bottleneck/prob16.pddl set &> ./tests/profile_results/bottleneck___prob16.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/cave-diving/dom05.pddl ../benchmarks/unsolve-ipc-2016/cave-diving/prob05.pddl set &> ./tests/profile_results/cave-diving___prob05.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/chessboard-pebbling/domain.pddl ../benchmarks/unsolve-ipc-2016/chessboard-pebbling/prob04.pddl set &> ./tests/profile_results/chessboard-pebbling___prob04.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/chessboard-pebbling/domain.pddl ../benchmarks/unsolve-ipc-2016/chessboard-pebbling/prob05.pddl set &> ./tests/profile_results/chessboard-pebbling___prob05.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/diagnosis/dom01.pddl ../benchmarks/unsolve-ipc-2016/diagnosis/prob01.pddl set &> ./tests/profile_results/diagnosis___prob01.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/document-transfer/domain.pddl ../benchmarks/unsolve-ipc-2016/document-transfer/prob05.pddl set &> ./tests/profile_results/document-transfer___prob05.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/over-nomystery/domain.pddl ../benchmarks/unsolve-ipc-2016/over-nomystery/prob01.pddl set &> ./tests/profile_results/over-nomystery___prob01.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/over-rovers/domain.pddl ../benchmarks/unsolve-ipc-2016/over-rovers/prob10.pddl set &> ./tests/profile_results/over-rovers___prob10.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/pegsol/domain.pddl ../benchmarks/unsolve-ipc-2016/pegsol/prob11.pddl set &> ./tests/profile_results/pegsol___prob11.pddl___log
./run.sh ../benchmarks/unsolve-ipc-2016/pegsol-row5/domain.pddl ../benchmarks/unsolve-ipc-2016/pegsol-row5/prob04.pddl set &> ./tests/profile_results/pegsol-row5___prob04.pddl___log
./run.sh ../benchmarks/decomposable/logistics00/domain.pddl ../benchmarks/decomposable/logistics00/problogistics-50-0.pddl set &> ./tests/profile_results/logistics00___problogistics-50-0.pddl___log
./run.sh ../benchmarks/decomposable/logistics00/domain.pddl ../benchmarks/decomposable/logistics00/problogistics-60-0.pddl set &> ./tests/profile_results/logistics00___problogistics-60-0.pddl___log
./run.sh ../benchmarks/decomposable/no-mystery/domain.pddl ../benchmarks/decomposable/no-mystery/prob10.pddl set &> ./tests/profile_results/no-mystery___prob10.pddl___log
./run.sh ../benchmarks/decomposable/no-mystery/domain.pddl ../benchmarks/decomposable/no-mystery/prob14.pddl set &> ./tests/profile_results/no-mystery___prob14.pddl___log
./run.sh ../benchmarks/decomposable/optical-telegraphs/domain.pddl ../benchmarks/decomposable/optical-telegraphs/sat-prob49.pddl set &> ./tests/profile_results/optical-telegraphs___sat-prob49.pddl___log
./run.sh ../benchmarks/decomposable/optical-telegraphs/domain.pddl ../benchmarks/decomposable/optical-telegraphs/unsat-prob2.pddl set &> ./tests/profile_results/optical-telegraphs___unsat-prob2.pddl___log
./run.sh ../benchmarks/decomposable/philosophers/domain.pddl ../benchmarks/decomposable/philosophers/prob10.pddl set &> ./tests/profile_results/philosophers___prob10.pddl___log
./run.sh ../benchmarks/decomposable/pipesworld-notankage/domain.pddl ../benchmarks/decomposable/pipesworld-notankage/p15-net2-b14-g4.pddl set &> ./tests/profile_results/pipesworld-notankage___p15-net2-b14-g4.pddl___log
./run.sh ../benchmarks/decomposable/pipesworld-tankage/domain.pddl ../benchmarks/decomposable/pipesworld-tankage/p10-net1-b14-g8-t50.pddl set &> ./tests/profile_results/pipesworld-tankage___p10-net1-b14-g8-t50.pddl___log
./run.sh ../benchmarks/decomposable/rovers/domain.pddl ../benchmarks/decomposable/rovers/p25.pddl set &> ./tests/profile_results/rovers___p25.pddl___log
./run.sh ../benchmarks/decomposable/rovers/domain.pddl ../benchmarks/decomposable/rovers/p31.pddl set &> ./tests/profile_results/rovers___p31.pddl___log
./run.sh ../benchmarks/decomposable/satellite/domain.pddl ../benchmarks/decomposable/satellite/p23-HC-pfile3.pddl set &> ./tests/profile_results/satellite___p23-HC-pfile3.pddl___log
./run.sh ../benchmarks/decomposable/storage/domain.pddl ../benchmarks/decomposable/storage/p12.pddl set &> ./tests/profile_results/storage___p12.pddl___log
./run.sh ../benchmarks/decomposable/tpp/domain.pddl ../benchmarks/decomposable/tpp/p18.pddl set &> ./tests/profile_results/tpp___p18.pddl___log
./run.sh ../benchmarks/decomposable/zenotravel/domain.pddl ../benchmarks/decomposable/zenotravel/pfile14.pddl set &> ./tests/profile_results/zenotravel___pfile14.pddl___log
./run.sh ../benchmarks/decomposable/zenotravel/domain.pddl ../benchmarks/decomposable/zenotravel/pfile19.pddl set &> ./tests/profile_results/zenotravel___pfile19.pddl___log
