#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HEURISTIC_NONE (111)
#define HEURISTIC_H_ADD (222)
#define HEURISTIC_NOVELTY (333)
#define HEURISTIC_RANDOM (444)

#define COMPRESS_ACTION (0)
#define COMPRESS_FULL_STATE (1)
#define COMPRESS_PARTIAL_STATE (2)
#endif
